In [ ]:
import numpy as np
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import warnings
warnings.filterwarnings("ignore")

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/DataScience/trabalho/titanic-tratado.csv',
                    encoding='utf-8')

In [ ]:
df.head()

PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0            2         1       1  female  38.0      1      0  71.2833        C
1            4         1       1  female  35.0      1      0  53.1000        S
2            7         0       1    male  54.0      0      0  51.8625        S
3           11         1       3  female   4.0      1      1  16.7000        S
4           12         1       1  female  58.0      0      0  26.5500        S

In [ ]:
df.shape

(183, 9)

Legenda

PassengerId: id do passageiro

Survived: número de sobreviventes

Pclass: classe do ingresso

Age: idade

SibSp: cônjuges e irmãos a bordo

Fare: tarifa de passageiros

Embarked: embarcados

Sex: sexo

Parch: número de pais e filhos a bordo

Transformando as variáveis categóricas nominais

In [42]:
df2 = pd.DataFrame.copy(df)

In [43]:
df2['Sex'].replace({'female':0, 'male': 1}, inplace=True)
df2['Embarked'].replace({'C': 0, 'Q': 1, 'S': 2}, inplace=True)

In [44]:
df2.head()

PassengerId  Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0            2         1       1    0  38.0      1      0  71.2833         0
1            4         1       1    0  35.0      1      0  53.1000         2
2            7         0       1    1  54.0      0      0  51.8625         2
3           11         1       3    0   4.0      1      1  16.7000         2
4           12         1       1    0  58.0      0      0  26.5500         2

In [45]:
df2.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Sex              int64
Age            float64
SibSp            int64
Parch            int64
Fare           float64
Embarked         int64
dtype: object

In [46]:
df2.shape

(183, 9)

In [47]:
# previsores & alvo
df2.head()

PassengerId  Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0            2         1       1    0  38.0      1      0  71.2833         0
1            4         1       1    0  35.0      1      0  53.1000         2
2            7         0       1    1  54.0      0      0  51.8625         2
3           11         1       3    0   4.0      1      1  16.7000         2
4           12         1       1    0  58.0      0      0  26.5500         2

In [48]:
previsores = df2.iloc[:, 0:8].values

In [49]:
previsores

array([[  2.    ,   1.    ,   1.    , ...,   1.    ,   0.    ,  71.2833],
       [  4.    ,   1.    ,   1.    , ...,   1.    ,   0.    ,  53.1   ],
       [  7.    ,   0.    ,   1.    , ...,   0.    ,   0.    ,  51.8625],
       ...,
       [880.    ,   1.    ,   1.    , ...,   0.    ,   1.    ,  83.1583],
       [888.    ,   1.    ,   1.    , ...,   0.    ,   0.    ,  30.    ],
       [890.    ,   1.    ,   1.    , ...,   0.    ,   0.    ,  30.    ]])

In [50]:
previsores.shape

(183, 8)

In [51]:
alvo = df2.iloc[:, 8].values

In [52]:
alvo

array([0, 2, 2, 2, 2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 2, 0, 0, 2, 2, 0, 2, 2,
       2, 2, 0, 2, 2, 2, 0, 0, 2, 2, 0, 0, 2, 0, 0, 0, 2, 2, 1, 2, 2, 2,
       2, 2, 2, 2, 2, 0, 2, 0, 0, 2, 0, 2, 0, 0, 0, 0, 2, 0, 0, 2, 0, 2,
       2, 2, 0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 2, 0, 2, 1, 2, 2, 2, 2, 2, 2,
       2, 0, 0, 2, 2, 2, 0, 0, 2, 0, 2, 0, 2, 2, 0, 2, 2, 2, 2, 0, 2, 0,
       2, 0, 0, 0, 2, 2, 2, 2, 0, 0, 2, 0, 0, 0, 2, 2, 2, 2, 2, 2, 0, 0,
       0, 0, 0, 2, 2, 0, 0, 2, 2, 0, 2, 0, 2, 2, 0, 2, 2, 0, 2, 2, 2, 0,
       2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 0, 2, 2,
       2, 2, 2, 2, 0, 2, 0])

In [53]:
alvo.shape

(183,)

Escalonamento

In [76]:
df2.describe()

PassengerId    Survived      Pclass         Sex         Age  \
count   183.000000  183.000000  183.000000  183.000000  183.000000   
mean    455.366120    0.672131    1.191257    0.519126   35.674426   
std     247.052476    0.470725    0.515187    0.501005   15.643866   
min       2.000000    0.000000    1.000000    0.000000    0.920000   
25%     263.500000    0.000000    1.000000    0.000000   24.000000   
50%     457.000000    1.000000    1.000000    1.000000   36.000000   
75%     676.000000    1.000000    1.000000    1.000000   47.500000   
max     890.000000    1.000000    3.000000    1.000000   80.000000   

            SibSp       Parch        Fare    Embarked  
count  183.000000  183.000000  183.000000  183.000000  
mean     0.464481    0.475410   78.682469    1.278689  
std      0.644159    0.754617   76.347843    0.957294  
min      0.000000    0.000000    0.000000    0.000000  
25%      0.000000    0.000000   29.700000    0.000000  
50%      0.000000    0.000000   57.000000    2.000000  
75%      1.000000    1.000000   90.000000    2.000000  
max      3.000000    4.000000  512.329200    2.000000

In [77]:
from sklearn.preprocessing import StandardScaler

In [78]:
previsores_esc = StandardScaler().fit_transform(previsores)

In [79]:
previsores_esc

array([[-1.84013507,  0.6984303 , -0.37225618, ...,  0.83362754,
        -0.63172982, -0.0971798 ],
       [-1.83201742,  0.6984303 , -0.37225618, ...,  0.83362754,
        -0.63172982, -0.3359971 ],
       [-1.81984093, -1.43178211, -0.37225618, ..., -0.7230443 ,
        -0.63172982, -0.35225028],
       ...,
       [ 1.72351585,  0.6984303 , -0.37225618, ..., -0.7230443 ,
         0.69708118,  0.05878503],
       [ 1.75598648,  0.6984303 , -0.37225618, ..., -0.7230443 ,
        -0.63172982, -0.63938976],
       [ 1.76410413,  0.6984303 , -0.37225618, ..., -0.7230443 ,
        -0.63172982, -0.63938976]])

In [80]:
previsoresdf = pd.DataFrame(previsores_esc)
previsoresdf

0         1         2         3         4         5         6  \
0   -1.840135  0.698430 -0.372256 -1.039012  0.149065  0.833628 -0.631730   
1   -1.832017  0.698430 -0.372256 -1.039012 -0.043230  0.833628 -0.631730   
2   -1.819841 -1.431782 -0.372256  0.962453  1.174636 -0.723044 -0.631730   
3   -1.803606  0.698430  3.520480 -1.039012 -2.030273  0.833628  0.697081   
4   -1.799547  0.698430 -0.372256 -1.039012  1.431029 -0.723044 -0.631730   
..        ...       ...       ...       ...       ...       ...       ...   
178  1.691045  0.698430 -0.372256 -1.039012  0.725949  0.833628  0.697081   
179  1.695104 -1.431782 -0.372256  0.962453 -0.171426 -0.723044 -0.631730   
180  1.723516  0.698430 -0.372256 -1.039012  1.302832 -0.723044  0.697081   
181  1.755986  0.698430 -0.372256 -1.039012 -1.068801 -0.723044 -0.631730   
182  1.764104  0.698430 -0.372256  0.962453 -0.620113 -0.723044 -0.631730   

            7  
0   -0.097180  
1   -0.335997  
2   -0.352250  
3   -0.814070  
4   -0.684702  
..        ...  
178 -0.343166  
179 -0.967737  
180  0.058785  
181 -0.639390  
182 -0.639390  

[183 rows x 8 columns]

In [81]:
#treino e teste
from sklearn.model_selection import train_test_split

In [82]:
x_treino, x_teste, y_treino, y_teste = train_test_split(previsores_esc, alvo, test_size = 0.3, random_state = 0)

In [83]:
x_treino.shape

(128, 8)

In [84]:
x_teste.shape

(55, 8)

In [85]:
y_treino.shape

(128,)

In [86]:
y_teste.shape

(55,)

Random Forest

In [87]:
from sklearn.ensemble import RandomForestClassifier

In [88]:
random = RandomForestClassifier(n_estimators=150, criterion='entropy', random_state = 0, max_depth=4)
random.fit(x_treino, y_treino)

RandomForestClassifier(criterion='entropy', max_depth=4, n_estimators=150,
                       random_state=0)

In [89]:
previsoes_random = random.predict(x_teste)
previsoes_random

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2,
       2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [90]:
y_teste

array([0, 2, 0, 2, 0, 2, 2, 0, 0, 0, 2, 0, 2, 0, 2, 2, 0, 2, 2, 0, 2, 2,
       0, 2, 2, 2, 0, 0, 2, 0, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 0, 0, 2,
       0, 0, 0, 0, 0, 2, 2, 2, 0, 0, 2])

In [91]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [92]:
print("Acurácia: %.2f%%" % (accuracy_score(y_teste, previsoes_random) * 100.0))

Acurácia: 54.55%


In [93]:
confusion_matrix(y_teste, previsoes_random)

array([[ 1, 23],
       [ 2, 29]])

In [94]:
print(classification_report(y_teste, previsoes_random))

              precision    recall  f1-score   support

           0       0.33      0.04      0.07        24
           2       0.56      0.94      0.70        31

    accuracy                           0.55        55
   macro avg       0.45      0.49      0.39        55
weighted avg       0.46      0.55      0.43        55



**Análise dados de treino**

In [95]:
previsoes_treino = random.predict(x_treino)
previsoes_treino

array([2, 2, 2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 0, 0, 2, 2, 0, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 0,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 2, 0, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 0,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 0, 2,
       2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [96]:
accuracy_score(y_treino, previsoes_treino)

0.7578125

In [97]:
confusion_matrix(y_treino, previsoes_treino)

array([[14,  0, 27],
       [ 0,  0,  2],
       [ 2,  0, 83]])